# Generated by Django 2.1.2 on 2018-10-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='turno',
            new_name='horario',
        ),
    ]
